name: LaTeX to PDF

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: exame.tex
        latexmk_use_xelatex: false    # Usar pdflatex (padrão)

    - name: Create deploy directory
      run: |
        mkdir -p public
        cp YOUR_FILE_NAME.pdf public/  # Substitua pelo nome real do PDF

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public