name: Compilar LaTeX e Publicar PDF

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Compilar LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: exame.tex
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode
          work_in_root_file_dir: true
          extra_system_packages: "texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra texlive-lang-portuguese"

      - name: Verificar se PDF foi gerado
        run: |
          if [ ! -f "exame.pdf" ]; then
            echo "Erro: Arquivo exame.pdf não foi gerado!"
            ls -al
            exit 1
          fi

      - name: Guardar PDF temporariamente
        run: |
          mkdir -p $GITHUB_WORKSPACE/output
          cp exame.pdf $GITHUB_WORKSPACE/output/

      - name: Publicar PDF no branch gh-pages
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git fetch
          git switch --orphan gh-pages
          rm -rf ./*
          cp $GITHUB_WORKSPACE/output/exame.pdf index.pdf
          git add index.pdf
          git commit -m 'Publicar PDF'
          git push -f origin gh-pages
