name: Compile LaTeX and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: exame.tex

      - name: Create deployment directory
        run: mkdir dist

      - name: Move PDF to deployment directory
        run: mv exame.pdf dist/

      - name: Create index.html
        run: |
          echo '<!DOCTYPE html>' > dist/index.html
          echo '<html lang="en">' >> dist/index.html
          echo '<head>' >> dist/index.html
          echo '    <meta http-equiv="refresh" content="0; url=exame.pdf" />' >> dist/index.html
          echo '    <title>Redirecting to PDF</title>' >> dist/index.html
          echo '</head>' >> dist/index.html
          echo '<body>' >> dist/index.html
          echo '    If you are not redirected automatically, <a href="exame.pdf">click here</a>.' >> dist/index.html
          echo '</body>' >> dist/index.html
          echo '</html>' >> dist/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist